name: PhpUnit tests

on: push
jobs:
  phpunit:
    runs-on: ubuntu-latest
    env:
      extensions: openssl, imagick
      key: cache-v20210425
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        php-versions: [ '7.3', '8.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 # https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}

      - name: Display informations
        run: |
          php -v
          composer --version

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies # https://github.com/shivammathur/setup-php#cache-composer-dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run PHPUnit
        run: |
          vendor/bin/phpunit --configuration phpunit.xml.dist --log-junit tmp/testsuites.xml

      - name: Persist test results
        uses: actions/upload-artifact@v2
        with:
          name: PHPUnit
          path: tmp/testsuites.xml

      - name: Tar failed test results
        if: failure()
        run: tar -cvf failed_test_results.tar tests/TestResults

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: FailedTests
          path: failed_test_results.tar

      - name: Run phpstan level Max
        run:
          composer run phpstan
